---
abstract: 'An effective SNMP-information-gathering module'
author:
  - 'Jan Henning Thorsen, C<< <pm at flodhest.net> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SNMP-Effective
no_index:
  directory:
    - examples
    - inc
    - t
  examples:
    - 0
recommends:
  Log::Log4perl: 0
requires:
  POSIX: 0
  SNMP: 0
  Tie::Array: 0
  Time::HiRes: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.0802
